config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "tickets#redirect"
  # get "/:classroom/:prenomnom/ticket", to: 'tickets#new'
  # get "/:classroom/tickets", to: 'tickets#index'
  resources :classrooms, only: :show do
    resources :tickets, only: [:index, :create, :new]
  end

  post "tickets/:id/done", to: "tickets#ending_ticket", as: "ending_ticket"
  post "tickets/:id/cancel", to: "tickets#cancel_ticket", as: "cancel_ticket"

  # mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/classroom.rb
class Classroom < ApplicationRecord
    enum city: [:ecully_a, :ecully_b, :paris, :st_etienne]

    has_many :tickets
    has_many :users
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  enum status: [:pending, :ended, :cancelled, :init]

  belongs_to :classroom
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  enum status: [:student, :teacher]

  has_many :tickets, inverse_of: :user
  belongs_to :classroom
  accepts_nested_attributes_for :tickets

  def position
    tickets = self.classroom.tickets.where(status: 0)
    tickets_users_ids = tickets.map { |t| t.user_id }
    pos = tickets_users_ids.find_index(self.id)
    if pos.nil?
      pos = 1
    else
      pos += 1
    end
    total = tickets.count

    pos
  end

  def current_tickets_count
    tickets = self.classroom.tickets.where(status: 0)
    tickets_users_ids = tickets.map { |t| t.user_id }
    pos = tickets_users_ids.find_index(self.id)
    if pos.nil?
      pos = 1
    else
      pos += 1
    end
    total = tickets.count

    total
  end

  def fullname
    return "#{self.prenom} #{self.nom}"
  end

  def fullname_tojs
    return "#{self.prenom}_#{self.nom}"
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_user!
end

app/controllers/classrooms_controller.rb
class ClassroomsController < ApplicationController
    def show
        if !current_user.teacher?
            flash.alert = "Tu n'avais rien à faire ici, petit malin."
            redirect_to root_path
            return
        end
        @classroom = Classroom.find(params[:id])

        if @classroom.id != current_user.classroom_id
            flash.alert = "Tu voulais changer de campus ? :D"
            redirect_to root_path
            return
        end
        
        @tickets = @classroom.tickets.where(status: "pending")
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
    def redirect
        classroom_id = current_user.classroom_id
        redirect_to new_classroom_ticket_path(classroom_id) if current_user.student?
        redirect_to classroom_path(classroom_id) if current_user.teacher?
    end

    def new
        if !current_user.student?
            flash.alert = "Tu voulais retourner à l'école ? :D"
            redirect_to root_path
            return
        end
        
        @classroom = Classroom.find(params["classroom_id"])
        @tickets = @classroom.tickets.where(status: "pending")

        if @classroom.id != current_user.classroom_id
            flash.alert = "Tu voulais changer de campus ? :D"
            redirect_to root_path
            return
        end

        @last_ticket = current_user.tickets.where(status: "pending").last
        @ticket = Ticket.new
    end

    def create
        if current_user.tickets.last.nil?
            # rien mais on passe, ça évite l'erreur du "no method pending? for nilclass"
        elsif current_user.tickets.last.pending?
            flash.alert = "Annule d'abord ton ticket avant d'en recréer un STP"
            redirect_to root_path    
            return
        end

        @classroom = Classroom.find(params[:classroom_id])
        @ticket = Ticket.new(ticket_params)
        @ticket.classroom = @classroom
        @ticket.user = current_user
        @ticket.status = 0
        if @ticket.save

            ClassroomChannel.broadcast_to(
                @classroom, 
                ["create", render_to_string(partial: "myticket", locals: {last_ticket: @ticket}), render_to_string(partial: "ticket", locals: {ticket: @ticket}), current_user.fullname]
            )   
            head :ok
            #render_to_string(partial: "myticket", locals: {ticket: @ticket})
            #redirect_to new_classroom_ticket_path(@classroom)
        else
            render new_classroom_ticket_path(@classroom), status: :unprocessable_entity
        end
    end

    def ending_ticket
        if !current_user.teacher?
            redirect_to root_path 
            return
        end

        ticket = Ticket.find(params[:id])

        if !ticket.pending?
            flash.alert = "#{ticket.user.prenom.capitalize} a annulé son ticket."
            redirect_to root_path 
            return
        end

        ticket.status = 1
        if ticket.save
            ClassroomChannel.broadcast_to(
                ticket.classroom, 
                ["valid", ticket.id, current_user.fullname]
            )
            head :ok
            #redirect_to classroom_path(ticket.classroom)
        end
    end

    def cancel_ticket
        if !current_user.student?
            redirect_to root_path 
            return
        end
        
        ticket = Ticket.find(params[:id])
        
        if current_user != ticket.user
            flash.alert = "Petit malin.. :p"
            redirect_to root_path 
            return
        end

        if !ticket.pending?
            flash.alert = "Ce ticket a été validé par un formateur"
            redirect_to root_path 
            return
        end

        ticket.status = 2
        if ticket.save
            ClassroomChannel.broadcast_to(
                ticket.classroom, 
                ["cancel", ticket.id, current_user.fullname_tojs]
            )
            head :ok
            #redirect_to root_path 
        end
    end

    private

    def ticket_params
        params.require(:ticket).permit(:content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/classrooms_helper.rb
module ClassroomsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/classrooms/show.html.erb
<%= render partial: "partials/menu" %>
<div class="container">
    <div class="row">
        <div class="twelves columns">
            <h1>#<%= @classroom.city %></h1>
            <%# <button onclick="location.reload()" class="button">Rafraîchir</button> %>
        </div>
    </div>    
    <br/>
    <span id="my-ticket"></span>
    <div class="row classroom" data-controller="classroom-subscription" data-classroom-subscription-classroom-id-value="<%= @classroom.id %>">
        <div id="ticketscontainer" class="twelves columns tickets" data-classroom-subscription-target="tickets">
            <% @tickets.each do |ticket| %>
                <%= render "tickets/ticket", ticket: ticket %>
            <% end %>
        </div>
        <div style="display:none;" data-classroom-subscription-target="myTicket">
            <% @tickets.each do |ticket| %>
                <%= render "tickets/ticket", ticket: ticket %>
            <% end %>
        </div>
    </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketsApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link href='https://unpkg.com/boxicons@2.1.4/css/boxicons.min.css' rel='stylesheet'>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_menu.html.erb
<div class="container">
    <div class="row">
        <%# L'ID fullname est très important pour le fonctionnement du websocket !! %>
        <i class='bx bxs-user-circle'></i><span id="fullname"><%= current_user.prenom %> <%= current_user.nom %></span>
        <br/>
        <%= link_to "Deconnexion", destroy_user_session_path, data: {turbo_method: :delete}, class: "button button-primary bg-red" %>
        <hr/>
        <p class="alert"><%= alert %></p>
        <p class="notice"><%= notice %></p>
    </div>
</div>

app/views/tickets/_myticket.html.erb
<% if !last_ticket.nil? %>
    <div id="ticket-<%= last_ticket.id %>">
        <span id="<%= current_user.prenom %>_<%= current_user.nom %>" class="bold"><%= current_user.prenom %> <%= current_user.nom %></span> <%= last_ticket.created_at.strftime("%a %b %e à %lh%M %p") %>
        <p><i class='bx bx-message-dots'></i> <%= last_ticket.content %></p>
        <br/>
        <%= link_to "Annuler mon Ticket", cancel_ticket_path(last_ticket), data: {turbo_method: :post}, class: "button button-primary bg-red" %>
        <!-- <span>Position dans la file: <span id="position"><%= current_user.position %></span>.</span> -->
    </div>
<% end %>

app/views/tickets/_ticket.html.erb
<div id="ticket-<%= ticket.id %>">
    <span id="<%= ticket.user.fullname_tojs %>" class="bold"><%= ticket.user.prenom %> <%= ticket.user.nom %></span>
    <i><%= ticket.created_at.strftime("%a %b %e à %lh%M %p") %></i>
    <p><i class='bx bx-message-dots'></i> <%= ticket.content %></p>
    <%= link_to "Marquer comme terminé", ending_ticket_path(ticket), data: {turbo_method: :post}, class: "button button-primary bg-green" %>
</div>

app/views/tickets/index.html.erb
Index Tickets

app/views/tickets/new.html.erb
<%= render partial: "partials/menu" %>

<div class="container">
    <span class="bold"><%= current_user.prenom %> <%= current_user.nom %></span>
    <br/>
    <%= simple_form_for [@classroom, @ticket], html: {class: ""} do |f| %>
        <%= f.input :content, label: false, placeholder: "Message ##{@classroom.city}", wrapper_html: {class: ""} %>
        <%= f.submit "Envoyer", class: "button-primary" %>
    <% end %>

    <div class="tickets" 
        data-controller="classroom-subscription"
        data-classroom-subscription-classroom-id-value="<%= @classroom.id %>"
    >
        <div id="my-ticket" data-classroom-subscription-target="myTicket">
            <%= render "tickets/myticket", last_ticket: @last_ticket %>
        </div>
        <div id="hidden-tickets" style="display:none;" data-classroom-subscription-target="tickets">
            <% @tickets.each do |ticket| %>
                <%= render "tickets/ticket", ticket: ticket %>
            <% end %>        
        </div>
    </div>    

</div>